spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/piston_protocol_db
    username: postgres
    password: secretpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration